package-lock.json
package.json
static/data/EclipseEvents.json

add missing timezones

---

static/data/EclipseEvents.json

fix date for date import

---

static/data/EclipseEvents.json

Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

#4 - Add EclipseCon 2020

---

content/2020/sam-iot/index.md
content/code-of-conduct/_index.md
data/en/2020/open-source-ai-workshop/registration.yml
data/en/2020/sam-iot/registration.yml

Code of Conduct for virtual events #22

---

Jenkinsfile

Signed-off-by: Mikaël Barbero <mikael.barbero@eclipse-foundation.org>

Improved build performances

---

content/2020/open-source-ai-workshop/_index.md

Update "About us" for AI workshop #30

---

content/2020/sam-iot/_index.md
content/2020/sam-iot/call-for-papers/_index.md
package-lock.json
package.json

Update content for SAMIoT 2020 Conference (Revision 1.1)-Target... #24

---

content/2020/sam-iot/_index.md
content/2020/sam-iot/call-for-papers/_index.md

We had to retrict the list to the people who signed the EDAS.
If this PR is accepted, I will be able to update regularly this list.
Thx

We had the restrict the TCP list

---

content/2020/sam-iot/_index.md
content/2020/sam-iot/call-for-papers/_index.md

Updated the TCP list + Left alignment of the date tables

---

content/2020/sam-iot/_index.md

Signed-off-by: Susan Iwai <susan.iwai@eclipse-foundation.org>

Update to registration info

---

content/2020/open-source-ai-workshop/_index.md

Update Open Source AI Workshop website now that event is over #42

---

content/2020/sam-iot/_index.md

Added 4 new members to the TCP

---

content/2020/sam-iot/_index.md
data/en/2020/sam-iot/agenda.yml

First version of the Agenda

---

content/2020/sam-iot/_index.md
content/2020/sam-iot/keynote.md
data/en/2020/sam-iot/keynote.yml

add speaker bio page

---

data/en/2020/sam-iot/keynote.yml

Signed-off-by: Susan Iwai <susan.iwai@eclipse-foundation.org>

Adding title and abstract to bio file.

---

content/2020/sam-iot/_index.md
data/en/2020/sam-iot/agenda.yml

Updated SAM IoT agenda to use new multiday functionality

---

content/2020/sam-iot/_index.md
content/2020/sam-iot/keynote.md

Signed-off-by: Susan Iwai <susan.iwai@eclipse-foundation.org>

Correcting typo in keynote title (plural)

---

package-lock.json
package.json

Hugo update theme fix for IE JS

---

content/2020/sam-iot/_index.md
data/en/2020/sam-iot/registration.yml

Closing the event

---

content/2020/sam-iot/_index.md

Adding  Alessio Angius to the TPC

---

js/components/EventHelpers.js
tests/events_tests/Events.test.js
tests/events_tests/TestEventsData.js

fix typo, missing s

---

js/components/CheckboxFilters.js
js/components/EventHelpers.js
js/components/EventsDataFetcher.js
less/events.less
tests/events_tests/EventHelpers.test.js

Fix #98 
add legend and fix alpha order, and add default bg, fix bg size with cover
TODO: 

add legend and fix alpha order, and add default bg, fix bg size with cover

---

js/components/EventCard.js
js/components/Events.js
less/events.less

use col-12 to utilize space, and increase the font size and card min-height

use col-12 to utilize space, and increase the font size and card min-height

---

js/components/EventCard.js
less/events.less
tests/events_tests/EventCard.test.js

add learn more button with infolink and change register button using register link

---

content/2020/sam-iot/_index.md
data/en/2020/sam-iot/agenda.yml

Added Rui video and updated the agenda section

---

data/en/2020/sam-iot/agenda.yml

Redirected the BRAIN-IoT presentation to the BRAIN-IoT SlideShare account (for KPIs)

---

.travis.yml
Dockerfile
Jenkinsfile
netlify.toml
package-lock.json
package.json

One of https://github.com/EclipseFdn/hugo-solstice-theme/issues/176

Update Hugo to 0.76.5 and theme to 0.0.102

---

content/2020/sam-iot/_index.md

Adding proceedings

---

content/2020/sam-iot/_index.md

Added a pointer to CEUR

---

content/2016/france/styles.css
content/2017/france/styles.css
content/2018/france/styles.css

Fix https://github.com/EclipseFdn/events.eclipse.org/issues/120#issuecomment-733717823

fix France footer social media icons not align correctly

---

data/en/2020/sam-iot/agenda.yml

Adding a CR after each paper link

---

config.toml

add download button #165

---

.travis.yml
Dockerfile
Jenkinsfile
NOTICE.md
babel.config.js
babel.config.json
js/App.js
netlify.toml
package-lock.json
package.json
webpack.mix.js

Update theme to 111

---

content/2021/saam-mobility/_index.md

Add new names on the TPC

---

js/components/EventHelpers.js
tests/events_tests/EventCard.test.js
tests/events_tests/EventHelpers.test.js

Add a "Research" Category in the events main page #179

---

content/2021/cn4ef-day/_index.md

Please add Register button to CN4EF website #218

---

content/2021/cn4ef-day/_index.md
layouts/shortcodes/cn4ef-day/about-the-event.html
layouts/shortcodes/cn4ef-day/event-hosted-by.html
less/cn4ef.less
package-lock.json
package.json

Fixes [issue220](https://github.com/EclipseFdn/events.eclipse.org/issues/220)

Update to CN4EF Day website

---

less/cn4ef.less

Fixes [issue223](https://github.com/EclipseFdn/events.eclipse.org/issues/223)

Updated logos sizes

---

data/en/2021/cn4ef-day/speakers.yml

Fixes [issue228](https://github.com/EclipseFdn/events.eclipse.org/issues/228)

Updated the speakers order
